name: Ruby Gem CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.3]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true


      - name: Install specific Bundler version
        run: gem install bundler -v 2.5.23

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec tests with documentation format
        run: bundle exec rspec --format documentation
