name: Ruby Gem CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.3]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false

      - name: Remove vendor/bundle cache folder
        run: rm -rf ./vendor/bundle

      - name: Install Bundler 2.5.23
        run: gem install bundler -v 2.5.23

      - name: Install dependencies with Bundler 2.5.23
        run: bundle _2.5.23_ install

      - name: Run tests with Bundler 2.5.23
        run: bundle _2.5.23_ exec rspec --format documentation
